### ISSUE TITLE
你好，可以将 npm 上 office-viewer 的包转到 fis-dev 帐号么？

### ISSUE THREAD

**Issue by nwind** [KillenMr/MadHatter#1]
不知道怎么联系，就发 issue 了。。

https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by KillenMr** [comment]
> 不知道怎么联系，就发 issue 了。。
> 
> https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

刚看到这条，我操作下
